# Generated by Django 5.0.14 on 2026-09-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("unidad", "Unidad"),
                            ("kg", "Kilogramo"),
                            ("lt", "Litro"),
                        ],
                        default="unidad",
                        max_length=10,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "default_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "is_active"],
                        name="catalog_pro_company_5de2e6_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="unique_company_sku"
            ),
        ),
    ]
