# Generated by Django 5.2.17 on 2026-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arriendo", "Arriendo"),
                    ("sueldos", "Sueldos"),
                    ("servicios", "Servicios"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
