# Generated by Django 5.2.17 on 2026-09-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnedPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=2000)),
                ("intent_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_phrases",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company"], name="assistant_l_company_b87e5f_idx"
                    )
                ],
            },
        ),
    ]
